version: '3'

services:
  tcp-udp-proxy:
    image: codejamninja/tcp-udp-proxy:latest
    ports:
      - 6888:6888
    environment:
      UPSTREAM: ssh:22
    links:
      - ssh:ssh

  ssh:
    image: arvindr226/alpine-ssh:latest
